spring:
  application:
    name: ECommercePurchase
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db?currentSchema=public
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
    platform: postgresql
    username: postgres
    password: p.postgres
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
cache:
  config:
    entryTtl: 60
server:
  port: 8080
com:
  ecommercepurchase:
    limit: 200
